Repository barrier-free-app/barrier-free-frontend, pull requests merged in 2025-05, with the labels that each got.

#3 [SETTING] #2 색상 세팅
  app/src/main/java/com/moduro/barrier_free_app/core_ui/theme/Color.kt
Labels: SETTING, 현진 🐬

#7 [FEAT] 디자인 시스템 폰트 정의 및 큰 글자 함수 구현
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/moduro/barrier_free_app/core_ui/theme/Type.kt
  app/src/main/res/font/suit_bold.otf
  app/src/main/res/font/suit_medium.otf
  app/src/main/res/font/suit_semibold.otf
Labels: 나현 🐳, FEAT

#6 [AUTH] #5 스플래시 구현
  app/src/main/java/com/moduro/barrier_free_app/presentation/auth/screen/SplashScreen.kt
  app/src/main/res/drawable/ic_start_logo.xml
Labels: 현진 🐬, AUTH
